[package]

name = "mydht"
version = "0.0.1"
authors = ["Emeric Chevalier <emericchevalier.pro@gmail.com>"]

[[bin]]
name = 'dhtmain'
doc = false

[[example]]
name='fileshare'
path = "examples/fs.rs"

[dependencies]

log = "0.3.0"
env_logger = "0.3.0"
uuid = "0.1.13"
num = "0.1.19"
rand = "0.3.3"
openssl = "0.5.2"
rust-crypto = "0.2.26"
#bencode = "0.1.9"
#bincode = "0.0.12"
rustc-serialize = "0.3.7"
time = "0.1.22"
byteorder = "0.3.3"

#[dependencies.semver]
#git = "https://github.com/...."

#[dependencies.protobuf]
#git = "https://github.com/stepancheg/rust-protobuf.git"

#[dependencies.capnp]
#git = "https://github.com/dwrensha/capnproto-rust.git"

#[dependencies.rust-crypto]
#git = "https://github.com/DaGenix/rust-crypto"



[dependencies.dht]
#path = "../mydht-dep/rust-dht/"
git = "https://github.com/cheme/rust-dht.git"

#[dependencies.time]
#git = "https://github.com/rust-lang/time.git"

#[dependencies.rustc-serialize]
#git = "https://github.com/rust-lang/rustc-serialize.git"

[dependencies.bencode]
#git = "https://github.com/arjantop/rust-bencode.git"
git = "https://github.com/cheme/rust-bencode.git"
#path = "../mydht-dep/rust-bencode/"

[dependencies.bincode]
git = "https://github.com/TyOverby/bincode.git"
#path = "../mydht-dep/bincode/"
