[package]
name = "mydht-externtransport"
version = "0.1.0"
authors = ["Emeric Chevalier <emericchevalier.pro@gmail.com>"]

[dependencies.mydht-base]
path = "../mydht-base/"
default-features = false

[dependencies.mydht-userpoll]
path = "../mydht-userpoll/"

